name       : syncthing-gtk
version    : 0.9.2.2
release    : 5
source     :
    - https://github.com/syncthing/syncthing-gtk/archive/v0.9.2.2.tar.gz : e63bc8e8697d7214cb7a7700113e0b3f82c4c5f90fb068dbdc14a2c690bef8df
license    : GPL-2.0
component  : network.download
summary    : GTK3 & Python based GUI and notification area icon for Syncthing
description: |
    GTK3 & Python based GUI and notification area icon for Syncthing
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(notify-python)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-2.7)
    - python-dateutil
    - python-setuptools
rundeps    :
    - notify-python
    - python-dateutil
    - python-gobject
    - python-inotify
    - python-six
    - syncthing
build      : |
    %python_setup
install    : |
    %python_install
