name       : syncthing-gtk
version    : 0.9.4.3
release    : 12
source     :
    - https://github.com/syncthing/syncthing-gtk/archive/v0.9.4.3.tar.gz : 058e13a8dd65c0024c92074dc5445b27278d71379d1843b7cbc84ee5c87afa12
license    : GPL-2.0-or-later
component  : network.download
summary    : GTK3 & Python based GUI and notification area icon for Syncthing
description: |
    GTK3 & Python based GUI and notification area icon for Syncthing
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(notify-python)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-2.7)
    - python-dateutil
    - python-setuptools
rundeps    :
    - notify-python
    - python-bcrypt
    - python-cairo
    - python-dateutil
    - python-gobject
    - python-inotify
    - python-six
    - syncthing
build      : |
    %python_setup
install    : |
    %python_install
