name       : syncthing-gtk
version    : 0.9.4.4
release    : 15
source     :
    - https://github.com/syncthing/syncthing-gtk/archive/v0.9.4.4.tar.gz : 896ddaaba4ad0b8f090c5a381a28b3da759932314562cdd50ca288543b03ddcc
license    : GPL-2.0-or-later
component  : network.download
summary    : GTK3 & Python based GUI and notification area icon for Syncthing
description: |
    GTK3 & Python based GUI and notification area icon for Syncthing
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(notify-python)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python-2.7)
    - python-dateutil
    - python-setuptools
rundeps    :
    - notify-python
    - python-bcrypt
    - python-cairo
    - python-dateutil
    - python-gobject
    - python-inotify
    - python-six
    - syncthing
build      : |
    %python_setup
install    : |
    %python_install
